name: tests

on: [pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    container:
      image: escolasoft1/laravel-prod-docker:fpm

    steps:
      - name: Install host app
        run: composer create-project --prefer-dist laravel/laravel host

      - name: Checkout the package
        uses: actions/checkout@v2
        with:
          path: host/package

      - name: Add composer.json repository
        working-directory: ./host
        run: composer config repositories.escolalms/auth path package

      - name: Require the package
        working-directory: ./host
        run: composer require escolalms/auth

      - name: Publish things
        working-directory: ./host
        run: php artisan migrate --seed

      - name: Run tests
        working-directory: ./host
        run: vendor/bin/phpunit package/tests
