name: tests

on: [ pull_request ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    container:
      image: escolasoft1/laravel-prod-docker:fpm

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
          MYSQL_PASSWORD: password
          MYSQL_USER: username
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install host app
        run: composer create-project --prefer-dist laravel/laravel host

      - name: Checkout the package
        uses: actions/checkout@v2
        with:
          path: host/package

      - name: Testing environment file
        run: cp host/package/.env.testing host/.env

      - name: Add composer.json repository
        working-directory: ./host
        run: composer config repositories.escolalms/auth path package

      - name: Require orchestra test package
        working-directory: ./host
        run: composer require orchestra/testbench

      - name: Require the package
        working-directory: ./host
        run: composer require escolalms/auth

      - name: Publish things
        working-directory: ./host
        run: php artisan migrate:fresh --seed

      - name: Passport install
        working-directory: ./host
        run: php artisan passport:install

      - name: Run tests
        working-directory: ./host
        run: vendor/bin/phpunit package/tests
