name: tests

on: [pull_request]

jobs:
  phpunit-mysql:
    runs-on: ubuntu-latest
    container:
      image: escolasoft1/laravel-prod-docker:fpm

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
          MYSQL_PASSWORD: password
          MYSQL_USER: username
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Setup environment
        run: cp .env.testing.mysql .env && cp .env.testing.mysql .env.testing && cp testbench.mysql.yaml testbench.yaml

      - name: Update composer
        run: composer update

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: vendor/bin/phpunit

  phpunit-postgres:
    runs-on: ubuntu-latest
    container:
      image: escolasoft1/laravel-prod-docker:fpm

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
          TZ: Europe/Warsaw
        ports:
          - 5432:5432

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Update composer
        run: composer update

      - name: Setup environment
        run: cp .env.testing.postgres .env && cp .env.testing.postgres .env.testing && cp testbench.postgres.yaml testbench.yaml

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: vendor/bin/phpunit
