name: tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install host app
        run: composer create-project --prefer-dist laravel/laravel host

      - name: Checkout the package
        uses: actions/checkout@v2
        with:
          path: host/package

      - name: Add composer.json repository
        working-directory: ./host
        run: composer config repositories.package path "../package"

      - name: Require the package
        working-directory: ./host
        run: composer requirepackage @dev

      - name: Publish things
        working-directory: ./host
        run: php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"

      - name: Publish things
        working-directory: ./host
        run: php artisan migrate --seed

      - name: Run tests
        working-directory: ./host
        run: vendor/bin/phpunit package/tests
