name: tests

on: [ pull_request ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    container:
      image: escolasoft1/laravel-prod-docker:fpm

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
          MYSQL_PASSWORD: password
          MYSQL_USER: username
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Instantiate package
        run: composer create-project --prefer-dist escolalms/auth host

      - name: Publish things
        working-directory: ./host
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        working-directory: ./host
        run: vendor/bin/phpunit
